language: go
dist: trusty
sudo: required
install: true
go:
  - 1.7.1
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.7.1
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
  - go env && pwd
  - mkdir -p $HOME/gopath/bin
script:
  - make build
deploy:
   provider: releases
  #api_key: "GITHUB OAUTH TOKEN"
   user: "prateekpandey14 "
   password: "@prateek1990"
   file: "pkg/"
   skip_cleanup: true
   on:
     tags: true 
  

